
const DATA=window.SKY_EXPLORER_DATA, VERSION=DATA.version, EARTH=12742, SUN=1392700, DEFAULT_LAT=52.085, DEFAULT_LON=4.883;
let objects=[...DATA.bodies.filter(o=>o.id!=="earth"),...DATA.stars];
const state={heading:100,rawHeading:100,pitch:28,rawPitch:28,headingOffset:0,pitchOffset:0,demo:true,motion:false,started:false,selected:"sun",locked:null,tab:"story",filter:"visible",stars:[],journey:null,step:0,flightFrom:null,flightTo:null,journeyRunning:false,journeyTimer:null,lat:DEFAULT_LAT,lon:DEFAULT_LON};
const $=id=>document.getElementById(id);
const el={start:$("start"),camera:$("camera"),starfield:$("starfield"),sky:$("skyLayer"),edge:$("edgeLayer"),guide:$("guideText"),toast:$("toast"),heading:$("headingChip"),gps:$("gpsChip"),calChip:$("calChip"),inspector:$("inspector"),selectedSphere:$("selectedSphere"),earthSphere:$("earthSphere"),sunSphere:$("sunSphere"),sunRefCol:$("sunRefCol"),selectedLabel:$("selectedLabel"),scaleMode:$("scaleMode"),objectGroup:$("objectGroup"),objectName:$("objectName"),objectSummary:$("objectSummary"),diameterFact:$("diameterFact"),earthRatioFact:$("earthRatioFact"),sunRatioFact:$("sunRatioFact"),distanceFact:$("distanceFact"),magFact:$("magFact"),positionFact:$("positionFact"),ratioBar:$("ratioBar"),tabPanel:$("tabPanel"),finder:$("finder"),search:$("search"),results:$("results"),calibrate:$("calibrate"),calStar:$("calStar"),calReadout:$("calReadout"),journey:$("journey"),journeyTitle:$("journeyTitle"),journeyDesc:$("journeyDesc"),journeyProgress:$("journeyProgress"),journeyStep:$("journeyStep"),journeyChoices:$("journeyChoices"),atlas:$("atlas"),atlasSearch:$("atlasSearch"),atlasResults:$("atlasResults"),orrery:$("orrery"),flightSvg:$("flightSvg"),flightPath:$("flightPath"),ship:$("ship")};
function norm(a){return((a%360)+360)%360}function delta(t,c){let d=norm(t)-norm(c);if(d>180)d-=360;if(d<-180)d+=360;return d}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function ratioEarth(o){return o.diameterKm?o.diameterKm/EARTH:null}function ratioSun(o){return o.diameterKm?o.diameterKm/SUN:null}
function scaleSizes(o){const rE=ratioEarth(o)||1,rS=ratioSun(o)||0;let selected=90,earth=32,sun=0,mode="Earth reference";if(o.id==="sun"){selected=170;earth=clamp(170*(EARTH/SUN),3,12);sun=0;mode="Sun vs Earth only"}else if(rS>1){sun=75;selected=clamp(75*Math.pow(rS,.48),82,190);earth=clamp(75*(EARTH/SUN),3,10);mode="Larger than Sun: compare with Sun + Earth"}else if(rS>0){sun=170;selected=clamp(170*rS,5,160);earth=clamp(170*(EARTH/SUN),3,12);mode="Compared within solar scale"}else if(rE<1){earth=120;selected=clamp(120*rE,8,120);sun=0;mode="Smaller than Earth"}return{selected,earth,sun,bar:clamp((Math.log10(rE||1)+1.5)/4*100,4,100),mode}}
function toast(m){el.toast.textContent=m;el.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("show"),2200)}function guide(m){el.guide.textContent=m}
function objectById(id){return objects.find(o=>o.id===id)||DATA.bodies.find(o=>o.id===id)||DATA.stars.find(o=>o.id===id)||DATA.catalog.find(o=>o.id===id)}
function buildSky(){el.sky.innerHTML="";objects.forEach(o=>{const b=document.createElement("button");b.className="sky-object";b.type="button";b.dataset.id=o.id;const isStar=o.group==="Milky Way";b.innerHTML=isStar?`<span class="star-dot texture-${o.texture}"></span><span class="object-label"><strong>${o.name}</strong><small>${o.constellation||o.type}</small></span>`:`<span class="orb texture-${o.texture}"></span><span class="object-label"><strong>${o.name}</strong><small>${o.type}</small></span>`;b.onclick=()=>openObject(o.id,true);el.sky.appendChild(b)})}
function posFor(o){const h=norm(state.heading+state.headingOffset),p=state.pitch+state.pitchOffset;const dx=delta(o.az,h),dy=o.alt-p;return{x:50+(dx/90)*50,y:50-(dy/50)*50,dx,dy,visible:Math.abs(dx)<90&&Math.abs(dy)<50}}
function render(){if(state.demo&&!state.motion){const t=performance.now()/1000;state.rawHeading=norm(110+Math.sin(t*.18)*75);state.rawPitch=28+Math.sin(t*.38)*8}state.heading=norm(state.heading+delta(state.rawHeading,state.heading)*.10);state.pitch+=(state.rawPitch-state.pitch)*.12;renderObjects();renderEdges();renderFlight();renderHud();drawStars();requestAnimationFrame(render)}
function renderObjects(){objects.forEach(o=>{const n=el.sky.querySelector(`[data-id="${o.id}"]`);if(!n)return;const p=posFor(o),edge=Math.max(Math.abs(p.dx)/90,Math.abs(p.dy)/50);n.style.setProperty("--x",p.x+"%");n.style.setProperty("--y",p.y+"%");n.style.setProperty("--s",clamp(1.08-edge*.10,.75,1.15));n.classList.toggle("visible",p.visible||!state.started);n.classList.toggle("selected",state.selected===o.id)})}
function renderEdges(){el.edge.innerHTML="";objects.map(o=>({...posFor(o),o,score:Math.abs(posFor(o).dx)+Math.abs(posFor(o).dy)*.8})).filter(x=>!x.visible).sort((a,b)=>a.o.id===state.locked?-1:b.o.id===state.locked?1:a.score-b.score).slice(0,7).forEach(item=>{const e=document.createElement("button");e.className="edge";e.type="button";const mx=innerWidth<740?52:76,my=innerWidth<740?104:90;let x=50+(item.dx/160)*50,y=50-(item.dy/100)*50;x=clamp(x,mx/innerWidth*100,100-mx/innerWidth*100);y=clamp(y,my/innerHeight*100,100-my/innerHeight*100);const arrow=Math.abs(item.dx)>Math.abs(item.dy)?item.dx>0?"→":"←":item.dy>0?"↑":"↓";e.style.left=x+"%";e.style.top=y+"%";e.innerHTML=`<i></i><span><strong>${item.o.name}</strong><small>${item.dx>0?"right":"left"} ${Math.round(Math.abs(item.dx))}°</small></span><b>${arrow}</b>`;e.onclick=()=>openObject(item.o.id,true);el.edge.appendChild(e)})}
function renderFlight(){if(!state.flightTo){el.flightSvg.classList.remove("active");el.ship.classList.remove("active");return}const to=objectById(state.flightTo),from=objectById(state.flightFrom)||objectById("sun");if(!to||!from)return;const a=posFor(from),b=posFor(to);const ax=clamp(a.x,8,92),ay=clamp(a.y,12,88),bx=clamp(b.x,8,92),by=clamp(b.y,12,88),mx=(ax+bx)/2,my=clamp((ay+by)/2-18,12,88);el.flightPath.setAttribute("d",`M ${ax} ${ay} Q ${mx} ${my} ${bx} ${by}`);el.flightSvg.classList.add("active");const t=(performance.now()/1650)%1;const x=(1-t)*(1-t)*ax+2*(1-t)*t*mx+t*t*bx,y=(1-t)*(1-t)*ay+2*(1-t)*t*my+t*t*by;el.ship.style.left=x+"%";el.ship.style.top=y+"%";el.ship.classList.add("active")}
function renderHud(){el.heading.textContent=`HDG ${Math.round(norm(state.heading+state.headingOffset))}°`;if(state.locked){const o=objectById(state.locked),p=posFor(o);guide(Math.abs(p.dx)<6&&Math.abs(p.dy)<6?`${o.name} centered.`:`Target ${o.name}: ${p.dx>0?"turn right":"turn left"} ${Math.round(Math.abs(p.dx))}°, ${p.dy>0?"tilt up":"tilt down"} ${Math.round(Math.abs(p.dy))}°.`)}}
function openObject(id,show){const o=objectById(id);if(!o)return;if(!objects.some(x=>x.id===id)&&id.startsWith("cat-")){objects.push(o);buildSky()}state.selected=id;el.objectGroup.textContent=o.group||o.type;el.objectName.textContent=o.name;el.objectSummary.textContent=o.summary;el.diameterFact.textContent=o.diameterKm?o.diameterKm.toLocaleString()+" km":"Unknown";const rE=ratioEarth(o),rS=ratioSun(o);el.earthRatioFact.textContent=rE?rE.toFixed(rE>10?1:2)+"×":"N/A";el.sunRatioFact.textContent=(o.id==="sun")?"—":(rS?rS.toFixed(rS>10?1:3)+"×":"N/A");el.distanceFact.textContent=o.distance||"Unknown";el.magFact.textContent=o.mag!=null?String(o.mag):"—";const p=posFor(o);el.positionFact.textContent=`${p.dx>0?"Right":"Left"} ${Math.round(Math.abs(p.dx))}° / ${p.dy>0?"Up":"Down"} ${Math.round(Math.abs(p.dy))}°`;el.selectedSphere.className=`sphere texture-${o.texture||"moon"}`;el.selectedLabel.textContent=o.name;const s=scaleSizes(o);el.selectedSphere.style.setProperty("--size",s.selected+"px");el.earthSphere.style.setProperty("--size",s.earth+"px");el.sunSphere.style.setProperty("--size",Math.max(s.sun,1)+"px");el.sunRefCol.classList.toggle("hidden",o.id==="sun"||s.sun===0);el.ratioBar.style.width=s.bar+"%";el.scaleMode.textContent=s.mode;renderTab(o);if(show){el.inspector.classList.add("open");el.finder.classList.remove("open");el.atlas.classList.remove("open")}}
function renderTab(o){document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===state.tab));if(state.tab==="story")el.tabPanel.textContent=o.summary;if(state.tab==="expert")el.tabPanel.innerHTML=`<b>Type:</b> ${o.type}<br><b>Group:</b> ${o.group||"Catalogue"}<br><b>Constellation:</b> ${o.constellation||"—"}<br><b>Spectral class:</b> ${o.spectral||"—"}<br><b>Expert note:</b> ${o.science||"Prototype object."}`;if(state.tab==="scale"){if(o.id==="sun")el.tabPanel.textContent="The Sun is compared only with Earth. It is about 109 Earth diameters wide.";else if(o.diameterKm)el.tabPanel.textContent=`${o.name} is ${(ratioEarth(o)).toFixed(ratioEarth(o)>10?1:2)} Earth diameters and ${(ratioSun(o)).toFixed(ratioSun(o)>10?1:3)} Sun diameters. Objects larger than the Sun show a Sun reference.`;else el.tabPanel.textContent="No trusted physical diameter yet; shown as catalogue object."}}
function launchAR(){state.started=true;state.demo=true;state.flightTo=null;state.locked=null;state.journeyRunning=false;clearInterval(state.journeyTimer);el.start.classList.add("hide");el.journey.classList.remove("open");el.atlas.classList.remove("open");el.calibrate.classList.remove("open");setRail("modeAR");toast("Stable AR launched");guide("AR is primary and active. Celestial bodies should be visible now.");}
async function startCamera(){launchAR();try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});el.camera.srcObject=s;el.camera.style.display="block";toast("Camera active")}catch(e){toast("Camera unavailable; visual AR remains active")}}
async function motion(){try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const p=await DeviceOrientationEvent.requestPermission();if(p!=="granted"){toast("Motion denied");return}}window.addEventListener("deviceorientation",e=>{if(typeof e.alpha==="number")state.rawHeading=norm(e.alpha);if(typeof e.beta==="number")state.rawPitch=clamp(90-Math.abs(e.beta),-25,75)},true);state.motion=true;state.demo=false;toast("Motion tracking enabled")}catch(e){toast("Motion unavailable")}}
function gps(){if(!navigator.geolocation){toast("GPS unavailable");return}navigator.geolocation.getCurrentPosition(p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;el.gps.textContent="GPS on";updateLiveSky(state.lat,state.lon);toast("GPS refined Sun, Moon and bright stars")},()=>toast("GPS denied; fallback remains active"),{enableHighAccuracy:true,timeout:10000})}
function updateLiveSky(lat,lon){const sun=objectById("sun"),moon=objectById("moon");Object.assign(sun,solar(new Date(),lat,lon));Object.assign(moon,moonApprox(new Date(),lat,lon));DATA.stars.forEach(s=>Object.assign(s,raDecToAltAz(new Date(),lat,lon,s.ra,s.dec)));}
function gmst(date){const d=(date-Date.UTC(2000,0,1,12))/86400000;return norm(280.46061837+360.98564736629*d)}
function raDecToAltAz(date,lat,lon,raHours,decDeg){const rad=Math.PI/180,deg=180/Math.PI;let ha=norm(gmst(date)+lon-raHours*15)*rad;if(ha>Math.PI)ha-=2*Math.PI;const dec=decDeg*rad,la=lat*rad;const alt=Math.asin(Math.sin(la)*Math.sin(dec)+Math.cos(la)*Math.cos(dec)*Math.cos(ha));const az=Math.atan2(-Math.sin(ha),Math.tan(dec)*Math.cos(la)-Math.sin(la)*Math.cos(ha));return{az:norm(az*deg),alt:clamp(alt*deg,-30,85)}}
function solar(date,lat,lon){const rad=Math.PI/180,day=Math.floor((date-Date.UTC(date.getUTCFullYear(),0,0))/86400000),h=date.getUTCHours()+date.getUTCMinutes()/60;const g=2*Math.PI/365*(day-1+(h-12)/24);const dec=.006918-.399912*Math.cos(g)+.070257*Math.sin(g)-.006758*Math.cos(2*g)+.000907*Math.sin(2*g)-.002697*Math.cos(3*g)+.00148*Math.sin(3*g);const eq=229.18*(.000075+.001868*Math.cos(g)-.032077*Math.sin(g)-.014615*Math.cos(2*g)-.040849*Math.sin(2*g));return horizontal(date,lat,lon,dec,eq)}
function moonApprox(date,lat,lon){const d=(date-Date.UTC(2000,0,1,12))/86400000,rad=Math.PI/180;const L=norm(218.316+13.176396*d),M=norm(134.963+13.064993*d),F=norm(93.272+13.229350*d);const lm=(L+6.289*Math.sin(M*rad))*rad,bm=5.128*Math.sin(F*rad)*rad,eps=23.439*rad;const dec=Math.asin(Math.sin(bm)*Math.cos(eps)+Math.cos(bm)*Math.sin(eps)*Math.sin(lm));const ra=Math.atan2(Math.sin(lm)*Math.cos(eps)-Math.tan(bm)*Math.sin(eps),Math.cos(lm));return horizontal(date,lat,lon,dec,0,ra)}
function horizontal(date,lat,lon,dec,eq=0,ra=null){const rad=Math.PI/180,deg=180/Math.PI;let ha;if(ra==null){const tst=(date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60+eq+4*lon)%1440;ha=(tst/4<0?tst/4+180:tst/4-180)*rad}else{ha=norm(gmst(date)+lon-ra*deg)*rad;if(ha>Math.PI)ha-=2*Math.PI}const la=lat*rad,alt=Math.asin(Math.sin(la)*Math.sin(dec)+Math.cos(la)*Math.cos(dec)*Math.cos(ha));const az=Math.atan2(-Math.sin(ha),Math.tan(dec)*Math.cos(la)-Math.sin(la)*Math.cos(ha));return{az:norm(az*deg),alt:clamp(alt*deg,-30,85)}}
function openCalibrate(){el.calibrate.classList.add("open");setRail("modeCal");el.calStar.innerHTML="";DATA.stars.slice().sort((a,b)=>a.mag-b.mag).forEach(s=>{const opt=document.createElement("option");opt.value=s.id;opt.textContent=`${s.name} · ${s.constellation} · mag ${s.mag}`;el.calStar.appendChild(opt)});el.calReadout.textContent=`Current calibration: heading offset ${Math.round(state.headingOffset)}°, pitch offset ${Math.round(state.pitchOffset)}°.`}
function alignStar(){const s=objectById(el.calStar.value);if(!s)return;state.headingOffset=delta(state.rawHeading,s.az);state.pitchOffset=s.alt-state.rawPitch;el.calChip.textContent=`CAL ${s.name}`;el.calReadout.textContent=`Aligned to ${s.name}. Heading offset ${Math.round(state.headingOffset)}°, pitch offset ${Math.round(state.pitchOffset)}°.`;toast(`Aligned to ${s.name}`)}
function resetCal(){state.headingOffset=0;state.pitchOffset=0;el.calChip.textContent="CAL off";el.calReadout.textContent="Calibration reset.";toast("Calibration reset")}
function renderFinder(){const q=el.search.value.toLowerCase().trim();let list=[];if(state.filter==="visible")list=objects;if(state.filter==="stars")list=DATA.stars.slice().sort((a,b)=>a.mag-b.mag);if(state.filter==="solar")list=DATA.bodies;if(state.filter==="all")list=[...objects,...DATA.catalog.slice(0,360)];if(q)list=[...objects,...DATA.catalog].filter(o=>(o.name+" "+o.type+" "+(o.constellation||"")+" "+(o.spectral||"")+" "+(o.science||"")).toLowerCase().includes(q)).slice(0,160);el.results.innerHTML="";list.forEach(o=>el.results.appendChild(card(o,()=>openObject(o.id,true))))}
function card(o,fn){const c=document.createElement("button");c.type="button";c.className="result-card";c.innerHTML=`<span class="result-dot"></span><span><strong>${o.name}</strong><small>${o.type} · ${o.constellation||o.group||"Atlas"}${o.mag!=null?" · mag "+o.mag:""}</small></span><b>→</b>`;c.onclick=fn;return c}
function openAtlas(){el.atlas.classList.add("open");renderAtlas();setRail("modeAtlas")}
function renderAtlas(){renderOrrery();const q=el.atlasSearch.value.toLowerCase().trim();const list=[...DATA.bodies,...DATA.stars,...DATA.catalog].filter(o=>(o.name+" "+o.type+" "+(o.constellation||"")+" "+(o.spectral||"")+" "+(o.science||"")).toLowerCase().includes(q)).slice(0,200);el.atlasResults.innerHTML="";list.forEach(o=>el.atlasResults.appendChild(card(o,()=>openObject(o.id,true))))}
function renderOrrery(){el.orrery.innerHTML="";DATA.bodies.filter(o=>["mercury","venus","earth","mars","jupiter","saturn","uranus","neptune"].includes(o.id)).forEach((o,i)=>{const size=72+i*37,path=document.createElement("div");path.className="orbit-path";path.style.width=size+"%";path.style.height=size+"%";el.orrery.appendChild(path);const b=document.createElement("button");b.className=`orbit-body texture-${o.texture}`;const angle=(i*48+Date.now()/80000*25)%360,r=size/2;b.style.left=`${50+Math.cos(angle*Math.PI/180)*r/2}%`;b.style.top=`${50+Math.sin(angle*Math.PI/180)*r/2}%`;const s=clamp(scaleSizes(o).selected/4,7,34);b.style.width=s+"px";b.style.height=s+"px";b.onclick=()=>openObject(o.id,true);el.orrery.appendChild(b)});const sun=document.createElement("button");sun.className="orbit-body texture-sun";sun.style.left="50%";sun.style.top="50%";sun.style.width="36px";sun.style.height="36px";sun.onclick=()=>openObject("sun",true);el.orrery.appendChild(sun)}
function startJourney(id="voyager"){const j=DATA.journeys.find(x=>x.id===id)||DATA.journeys[0];state.journey=j;state.step=0;state.journeyRunning=true;el.journey.classList.add("open");setRail("modeJourney");renderJourney();clearInterval(state.journeyTimer);state.journeyTimer=setInterval(()=>{if(state.journeyRunning)nextStep()},9000)}
function renderJourney(){const j=state.journey;if(!j)return;const target=objectById(j.steps[state.step]);const prev=objectById(j.steps[Math.max(0,state.step-1)])||objectById("sun");el.journeyTitle.textContent=j.title;el.journeyDesc.textContent=j.description;el.journeyProgress.style.width=((state.step+1)/j.steps.length*100)+"%";el.journeyStep.innerHTML=`<b>Flight ${state.step+1}/${j.steps.length}: ${target.name}</b><br>${target.summary}<br><span class="kicker">Optional Voyager. AR remains available underneath.</span>`;el.journeyChoices.innerHTML="";DATA.journeys.forEach(x=>el.journeyChoices.appendChild(card({name:x.title,type:x.description,group:"Journey"},()=>startJourney(x.id))));state.flightFrom=prev.id;state.flightTo=target.id;state.locked=target.id;openObject(target.id,false)}
function nextStep(){if(!state.journey)return startJourney();state.step=(state.step+1)%state.journey.steps.length;renderJourney()}
function pauseJourney(){state.journeyRunning=!state.journeyRunning;el.pauseJourney.textContent=state.journeyRunning?"Pause":"Resume";toast(state.journeyRunning?"Voyager resumed":"Voyager paused")}
function setRail(id){document.querySelectorAll(".rail-btn").forEach(r=>r.classList.remove("active"));$(id).classList.add("active")}
function setupStars(){const c=el.starfield,r=Math.min(devicePixelRatio||1,2);c.width=Math.floor(innerWidth*r);c.height=Math.floor(innerHeight*r);c.style.width=innerWidth+"px";c.style.height=innerHeight+"px";state.stars=Array.from({length:420},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.4+.2,a:Math.random()*.75+.15}))}
function drawStars(){const c=el.starfield,ctx=c.getContext("2d");if(!ctx)return;const r=Math.min(devicePixelRatio||1,2);ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.scale(r,r);const px=delta(state.heading,180)*.25,py=state.pitch*-.6;state.stars.forEach(s=>{const x=((s.x*innerWidth+px)%innerWidth+innerWidth)%innerWidth,y=((s.y*innerHeight+py)%innerHeight+innerHeight)%innerHeight;ctx.globalAlpha=s.a;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fill()});ctx.restore()}
document.addEventListener("click",e=>{const close=e.target.closest("[data-close]");if(close)$(close.dataset.close).classList.remove("open")});
$("launchBtn").onclick=launchAR;$("cameraBtn").onclick=startCamera;$("motionBtn")&&($("motionBtn").onclick=motion);$("gpsBtn").onclick=gps;$("calBtn").onclick=openCalibrate;$("atlasBtn").onclick=openAtlas;$("voyagerBtn").onclick=()=>startJourney("voyager");$("finderBtn").onclick=()=>{el.finder.classList.add("open");renderFinder()};$("modeAtlas").onclick=openAtlas;$("modeJourney").onclick=()=>startJourney("voyager");$("modeCal").onclick=openCalibrate;$("modeAR").onclick=()=>{state.flightTo=null;state.locked=null;el.atlas.classList.remove("open");el.journey.classList.remove("open");el.calibrate.classList.remove("open");setRail("modeAR");guide("AR mode active. Journey is off.")};$("lockBtn").onclick=()=>{state.locked=state.selected;state.flightTo=state.selected;toast("Target locked")};$("useJourneyBtn").onclick=()=>startJourney("voyager");$("nextStep").onclick=nextStep;$("pauseJourney").onclick=pauseJourney;$("backToAR").onclick=()=>el.atlas.classList.remove("open");$("alignStarBtn").onclick=alignStar;$("resetCalBtn").onclick=resetCal;$("brand").onclick=()=>guide(`${VERSION}. Stable AR is the primary mode.`);el.search.oninput=renderFinder;el.atlasSearch.oninput=renderAtlas;document.querySelectorAll(".filter").forEach(f=>f.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));f.classList.add("active");state.filter=f.dataset.filter;renderFinder()});document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;renderTab(objectById(state.selected))});window.addEventListener("resize",setupStars);
buildSky();setupStars();updateLiveSky(DEFAULT_LAT,DEFAULT_LON);renderFinder();renderAtlas();openObject("sun",false);requestAnimationFrame(render);
