
const DATA=window.SKY_EXPLORER_DATA||{bodies:[],catalog:[],tours:[]};
const EARTH_DIAMETER=12742;
const state={headingRaw:95,pitchRaw:18,heading:95,pitch:18,offset:0,demo:false,motion:false,selected:"sun",locked:null,tab:"story",filter:"featured",stars:[],demoStart:0,lat:null,lon:null};
let objects=[...DATA.bodies.filter(o=>o.id!=="earth")];
const $=id=>document.getElementById(id);
const el={camera:$("camera"),start:$("startScreen"),stars:$("stars"),sky:$("skyLayer"),edge:$("edgeLayer"),heading:$("headingChip"),pitch:$("pitchChip"),gps:$("gpsChip"),compass:$("compassTrack"),guide:$("guideText"),toast:$("toast"),inspector:$("inspector"),sphere:$("bigSphere"),earth:$("earthSphere"),type:$("objectType"),name:$("objectName"),summary:$("summary"),diam:$("diameterMetric"),ratio:$("earthRatioMetric"),pos:$("positionMetric"),bar:$("scaleBar"),label:$("selectedScaleLabel"),panel:$("tabPanel"),finder:$("finder"),search:$("search"),targetList:$("targetList"),tours:$("tours"),tourList:$("tourList"),explore:$("explore"),exploreSearch:$("exploreSearch"),exploreList:$("exploreList"),orrery:$("orrery")};
function norm(a){return((a%360)+360)%360}
function delta(t,c){let d=norm(t)-norm(c);if(d>180)d-=360;if(d<-180)d+=360;return d}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function lerpAngle(c,t,a){return norm(c+delta(t,c)*a)}
function toast(m){el.toast.textContent=m;el.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("show"),2000)}
function guide(m){el.guide.textContent=m}
function bodyById(id){return objects.find(o=>o.id===id)||DATA.bodies.find(o=>o.id===id)||DATA.catalog.find(o=>o.id===id)}
function earthRatio(o){return o.diameterKm?o.diameterKm/EARTH_DIAMETER:null}
function compressedSize(o){const r=earthRatio(o);if(!r)return 58;return clamp(28*Math.pow(r,.42),18,190)}
function buildSky(){el.sky.innerHTML="";objects.forEach(o=>{const b=document.createElement("button");b.type="button";b.className="sky-object";b.dataset.id=o.id;b.innerHTML=`<span class="mini-sphere mini-${o.texture}"></span><span class="label"><strong>${o.name}</strong><small>${o.type}</small></span>`;b.onclick=()=>openObject(o.id,true);el.sky.appendChild(b)})}
function render(){if(state.demo&&!state.motion){const t=(performance.now()-state.demoStart)/1000;state.headingRaw=norm(95+Math.sin(t*.35)*170+t*4);state.pitchRaw=22+Math.sin(t*.7)*18}state.heading=lerpAngle(state.heading,norm(state.headingRaw+state.offset),.12);state.pitch+=(state.pitchRaw-state.pitch)*.14;renderObjects();renderEdges();renderHud();drawStars();requestAnimationFrame(render)}
function renderObjects(){const fovX=60,fovY=48;objects.forEach(o=>{const n=el.sky.querySelector(`[data-id="${o.id}"]`);if(!n)return;const dx=delta(o.az,state.heading),dy=o.alt-state.pitch;const vis=Math.abs(dx)<=fovX/2&&Math.abs(dy)<=fovY/2;const x=50+(dx/(fovX/2))*50,y=50-(dy/(fovY/2))*50,edge=Math.max(Math.abs(dx)/(fovX/2),Math.abs(dy)/(fovY/2));n.style.setProperty("--x",`${x}%`);n.style.setProperty("--y",`${y}%`);n.style.setProperty("--scale",`${clamp(1.08-edge*.18,.68,1.12)}`);n.classList.toggle("visible",vis);n.classList.toggle("selected",state.selected===o.id)})}
function renderEdges(){el.edge.innerHTML="";const fovX=60,fovY=48;objects.map(o=>{const dx=delta(o.az,state.heading),dy=o.alt-state.pitch;return{o,dx,dy,vis:Math.abs(dx)<=fovX/2&&Math.abs(dy)<=fovY/2,score:Math.abs(dx)+Math.abs(dy)*.8}}).filter(x=>!x.vis).sort((a,b)=>a.o.id===state.locked?-1:b.o.id===state.locked?1:a.score-b.score).slice(0,6).forEach(item=>{const e=document.createElement("button");e.type="button";e.className="edge";const mx=innerWidth<740?52:74,my=innerWidth<740?102:88;let x=50+(item.dx/140)*50,y=50-(item.dy/100)*50;x=clamp(x,mx/innerWidth*100,100-mx/innerWidth*100);y=clamp(y,my/innerHeight*100,100-my/innerHeight*100);if(Math.abs(item.dx)>Math.abs(item.dy)*1.1)x=item.dx<0?mx/innerWidth*100:100-mx/innerWidth*100;else y=item.dy>0?my/innerHeight*100:100-my/innerHeight*100;const arrow=Math.abs(item.dx)>Math.abs(item.dy)?item.dx>0?"→":"←":item.dy>0?"↑":"↓";e.style.left=`${x}%`;e.style.top=`${y}%`;e.innerHTML=`<span class="edge-dot"></span><span><strong>${item.o.name}</strong><small>${item.dx>0?"right":"left"} ${Math.round(Math.abs(item.dx))}°</small></span><b>${arrow}</b>`;e.onclick=()=>openObject(item.o.id,true);el.edge.appendChild(e)})}
function renderHud(){el.heading.textContent=`HDG ${Math.round(state.heading)}°`;el.pitch.textContent=`PIT ${Math.round(state.pitch)}°`;el.compass.style.transform=`translateX(${delta(0,state.heading)*-1.05}px)`;if(state.locked){const o=bodyById(state.locked);const dx=delta(o.az,state.heading),dy=o.alt-state.pitch;guide(Math.abs(dx)<5&&Math.abs(dy)<5?`${o.name} centered.`:`Locked on ${o.name}: ${dx>0?"turn right":"turn left"} ${Math.round(Math.abs(dx))}°, ${dy>0?"tilt up":"tilt down"} ${Math.round(Math.abs(dy))}°.`)}}
async function startCamera(){el.start.classList.add("hide");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});el.camera.srcObject=s;el.camera.style.display="block";toast("Camera active")}catch(e){toast("Camera unavailable; visual AR active")}}
async function enableMotion(){try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const p=await DeviceOrientationEvent.requestPermission();if(p!=="granted"){toast("Motion denied");return}}window.addEventListener("deviceorientation",e=>{if(typeof e.alpha==="number")state.headingRaw=norm(e.alpha);if(typeof e.beta==="number")state.pitchRaw=clamp(90-Math.abs(e.beta),-25,75)},true);state.motion=true;state.demo=false;toast("Motion tracking enabled")}catch(e){toast("Motion unavailable")}}
function demo(){el.start.classList.add("hide");state.demo=true;state.demoStart=performance.now();toast("Demo sweep active");guide("Demo Sweep active. Select objects or use Explore Mode for non-AR research.")}
function gps(){if(!navigator.geolocation){toast("GPS unavailable");return}navigator.geolocation.getCurrentPosition(p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;el.gps.textContent="GPS on";updateLivePositions();toast("GPS enabled; Sun and Moon refined")},()=>toast("GPS denied"))}
function updateLivePositions(){if(state.lat==null)return;const sun=objects.find(o=>o.id==="sun"),moon=objects.find(o=>o.id==="moon");if(sun)Object.assign(sun,solar(new Date(),state.lat,state.lon));if(moon)Object.assign(moon,moonApprox(new Date(),state.lat,state.lon))}
function solar(date,lat,lon){const rad=Math.PI/180,deg=180/Math.PI;const day=Math.floor((date-Date.UTC(date.getUTCFullYear(),0,0))/86400000);const h=date.getUTCHours()+date.getUTCMinutes()/60;const g=2*Math.PI/365*(day-1+(h-12)/24);const dec=.006918-.399912*Math.cos(g)+.070257*Math.sin(g)-.006758*Math.cos(2*g)+.000907*Math.sin(2*g)-.002697*Math.cos(3*g)+.00148*Math.sin(3*g);const eq=229.18*(.000075+.001868*Math.cos(g)-.032077*Math.sin(g)-.014615*Math.cos(2*g)-.040849*Math.sin(2*g));return horizontal(date,lat,lon,dec,eq)}
function moonApprox(date,lat,lon){const days=(date-Date.UTC(2000,0,1,12))/86400000;const L=norm(218.316+13.176396*days);const M=norm(134.963+13.064993*days);const F=norm(93.272+13.229350*days);const lonM=(L+6.289*Math.sin(M*Math.PI/180))*Math.PI/180;const latM=(5.128*Math.sin(F*Math.PI/180))*Math.PI/180;const eps=23.439*Math.PI/180;const dec=Math.asin(Math.sin(latM)*Math.cos(eps)+Math.cos(latM)*Math.sin(eps)*Math.sin(lonM));const ra=Math.atan2(Math.sin(lonM)*Math.cos(eps)-Math.tan(latM)*Math.sin(eps),Math.cos(lonM));return horizontal(date,lat,lon,dec,0,ra)}
function horizontal(date,lat,lon,dec,eq=0,ra=null){const rad=Math.PI/180,deg=180/Math.PI;let ha;if(ra==null){const tst=(date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60+eq+4*lon)%1440;ha=(tst/4<0?tst/4+180:tst/4-180)*rad}else{const d=(date-Date.UTC(2000,0,1,12))/86400000;const gmst=norm(280.46061837+360.98564736629*d);ha=(norm(gmst+lon-ra*deg))*rad;if(ha>Math.PI)ha-=2*Math.PI}const la=lat*rad;const alt=Math.asin(Math.sin(la)*Math.sin(dec)+Math.cos(la)*Math.cos(dec)*Math.cos(ha));const az=Math.atan2(-Math.sin(ha),Math.tan(dec)*Math.cos(la)-Math.sin(la)*Math.cos(ha));return{az:norm(az*deg),alt:clamp(alt*deg,-30,85)}}
function openObject(id,show){const o=bodyById(id);if(!o)return;state.selected=id;el.type.textContent=o.type;el.name.textContent=o.name;el.summary.textContent=o.summary;el.diam.textContent=o.diameterKm?`${o.diameterKm.toLocaleString()} km`:"Catalog";const r=earthRatio(o);el.ratio.textContent=r?`${r.toFixed(r>10?1:2)}× Earth`:"N/A";const dx=delta(o.az||0,state.heading),dy=(o.alt||0)-state.pitch;el.pos.textContent=`${dx>0?"Right":"Left"} ${Math.round(Math.abs(dx))}° / ${dy>0?"Up":"Down"} ${Math.round(Math.abs(dy))}°`;el.sphere.className=`sphere texture-${o.texture||"moon"}`;el.sphere.style.setProperty("--size",`${compressedSize(o)}px`);el.label.textContent=o.name;el.bar.style.width=`${clamp((r||.2)/12*100,4,100)}%`;renderTab(o);guide(`${o.name}: ${o.story||o.summary}`);if(show){el.inspector.classList.add("open");el.finder.classList.remove("open");el.tours.classList.remove("open")}}
function renderTab(o){document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===state.tab));if(state.tab==="story")el.panel.textContent=o.story||o.summary;if(state.tab==="data")el.panel.innerHTML=`<b>Distance:</b> ${o.distance||"Unknown"}<br><b>Mass:</b> ${o.mass||"Unknown"}<br><b>Rotation:</b> ${o.rotation||"Unknown"}<br><b>Engine:</b> ${o.engine||"catalog"}`;if(state.tab==="scale"){const r=earthRatio(o);el.panel.textContent=r?`True diameter ratio: ${o.name} is ${r.toFixed(r>10?1:2)} Earth diameters. The visual uses compressed proportional scaling so the Sun does not consume the whole screen.`:"No reliable physical diameter yet for this catalogue object."}}
function openFinder(){el.finder.classList.add("open");el.inspector.classList.remove("open");el.tours.classList.remove("open");renderTargets()}
function renderTargets(){const q=el.search.value.toLowerCase().trim();let list=state.filter==="featured"?objects:state.filter==="solar"?objects.filter(o=>o.type.includes("Planet")||o.type==="Star"||o.type.includes("satellite")):state.filter==="deep"?DATA.catalog.filter(o=>["Galaxy","Nebula","Exoplanet System","Quasar","Pulsar"].includes(o.type)).slice(0,200):[...objects,...DATA.catalog.slice(0,300)];if(q)list=[...objects,...DATA.catalog].filter(o=>(o.name+" "+o.type+" "+(o.constellation||"")).toLowerCase().includes(q)).slice(0,80);el.targetList.innerHTML="";list.forEach(item=>el.targetList.appendChild(card(item,()=>selectTarget(item))))}
function card(item,fn){const c=document.createElement("button");c.type="button";c.className="target-card";const dx=delta(item.az||0,state.heading);c.innerHTML=`<span class="target-dot"></span><span><strong>${item.name}</strong><small>${item.type}${item.constellation?" · "+item.constellation:""}</small></span><b>${Math.abs(dx)<8?"•":dx>0?"→":"←"}</b>`;c.onclick=fn;return c}
function selectTarget(item){if(!objects.some(o=>o.id===item.id)&&item.id.startsWith("cat-")){objects.push({...item,diameterKm:null,texture:item.texture||"moon",engine:"catalog"});buildSky()}openObject(item.id,true)}
function renderTours(){el.tourList.innerHTML="";DATA.tours.forEach(t=>el.tourList.appendChild(card({name:t.title,type:`${t.level} · ${t.duration}`,az:state.heading},()=>{el.tours.classList.remove("open");guide(`${t.title}: ${t.description}`);toast("Journey selected")})))}
function openExplore(){el.start.classList.add("hide");el.explore.classList.add("open");renderOrrery();renderExploreList()}
function renderOrrery(){el.orrery.innerHTML="";const solar=DATA.bodies.filter(o=>["mercury","venus","earth","mars","jupiter","saturn","uranus","neptune"].includes(o.id));const cx=50,cy=50;solar.forEach((o,i)=>{const size=70+i*38;const path=document.createElement("div");path.className="orbit-path";path.style.width=size+"%";path.style.height=size+"%";el.orrery.appendChild(path);const body=document.createElement("button");body.type="button";body.className=`orbit-body texture-${o.texture}`;const angle=(i*47+Date.now()/90000*20)%360;const r=size/2;body.style.left=`${cx+Math.cos(angle*Math.PI/180)*r/2}%`;body.style.top=`${cy+Math.sin(angle*Math.PI/180)*r/2}%`;const s=clamp(compressedSize(o)/4,8,34);body.style.width=s+"px";body.style.height=s+"px";body.onclick=()=>openObject(o.id,true);el.orrery.appendChild(body)});const sun=document.createElement("button");sun.type="button";sun.className="orbit-body texture-sun";sun.style.left="50%";sun.style.top="50%";sun.style.width="34px";sun.style.height="34px";sun.onclick=()=>openObject("sun",true);el.orrery.appendChild(sun)}
function renderExploreList(){const q=el.exploreSearch.value.toLowerCase().trim();const list=[...DATA.bodies,...DATA.catalog].filter(o=>(o.name+" "+o.type+" "+(o.constellation||"")).toLowerCase().includes(q)).slice(0,140);el.exploreList.innerHTML="";list.forEach(item=>el.exploreList.appendChild(card(item,()=>selectTarget(item))))}
function setupStars(){const c=el.stars,r=Math.min(devicePixelRatio||1,2);c.width=Math.floor(innerWidth*r);c.height=Math.floor(innerHeight*r);c.style.width=innerWidth+"px";c.style.height=innerHeight+"px";state.stars=Array.from({length:280},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.5+.18,a:Math.random()*.75+.16}))}
function drawStars(){const c=el.stars,ctx=c.getContext("2d");if(!ctx)return;const r=Math.min(devicePixelRatio||1,2);ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.scale(r,r);const px=delta(state.heading,180)*.42,py=state.pitch*-.9;state.stars.forEach(s=>{const x=((s.x*innerWidth+px)%innerWidth+innerWidth)%innerWidth,y=((s.y*innerHeight+py)%innerHeight+innerHeight)%innerHeight;ctx.globalAlpha=s.a;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fill()});ctx.restore()}
document.addEventListener("click",e=>{const btn=e.target.closest("[data-close]");if(btn){const id=btn.dataset.close;const node=$(id);if(node)node.classList.remove("open")}})
$("startAR").onclick=async()=>{await startCamera();await enableMotion()};$("startDemo").onclick=demo;$("startExplore").onclick=openExplore;$("arBtn").onclick=startCamera;$("motionBtn").onclick=enableMotion;$("gpsBtn").onclick=gps;$("exploreBtn").onclick=openExplore;$("tourBtn").onclick=()=>{el.tours.classList.add("open");el.finder.classList.remove("open");el.inspector.classList.remove("open")};$("finderBtn").onclick=openFinder;$("backToAR").onclick=()=>el.explore.classList.remove("open");$("lockBtn").onclick=()=>{state.locked=state.selected;toast("Target locked")};$("journeyBtn").onclick=()=>guide("Cosmic Journey preview: scale, distance and story become a guided premium sequence.");$("homeBtn").onclick=()=>guide("Primary mode: AR. Secondary mode: Explore. USP: visible and invisible universe.");el.search.oninput=renderTargets;el.exploreSearch.oninput=renderExploreList;document.querySelectorAll(".filter").forEach(f=>f.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));f.classList.add("active");state.filter=f.dataset.filter;renderTargets()});document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;const o=bodyById(state.selected);if(o)renderTab(o)});window.addEventListener("resize",setupStars);
buildSky();renderTours();setupStars();openObject("sun",false);requestAnimationFrame(render);setInterval(()=>{if(el.explore.classList.contains("open"))renderOrrery()},1500);
